# Generated by Django 5.0.6 on 2025-11-02 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=128)),
                ('street_number', models.CharField(max_length=16)),
                ('city_code', models.CharField(db_index=True, max_length=16)),
                ('city', models.CharField(db_index=True, max_length=64)),
                ('country', models.CharField(db_index=True, max_length=64)),
            ],
            options={
                'indexes': [models.Index(fields=['city', 'city_code'], name='idx_city_citycode')],
            },
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=64)),
                ('last_name', models.CharField(db_index=True, max_length=64)),
                ('gender', models.CharField(choices=[
                 ('m', 'Male'), ('f', 'Female'), ('o', 'Other')], db_index=True, max_length=1)),
                ('customer_id', models.CharField(db_index=True, max_length=64)),
                ('phone_number', models.CharField(db_index=True, max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_updated', models.DateTimeField(
                    auto_now=True, db_index=True)),
                ('birthday', models.DateField(blank=True, db_index=True, null=True)),
                ('address', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.address')),
            ],
            options={
                'verbose_name': 'App User',
                'verbose_name_plural': 'App Users',
            },
        ),
        migrations.CreateModel(
            name='CustomerRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_activity', models.DateTimeField(db_index=True)),
                ('appuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                 related_name='relationship', to='core.appuser')),
            ],
            options={
                'verbose_name': 'Customer Relationship',
                'verbose_name_plural': 'Customer Relationships',
            },
        ),
        migrations.AddIndex(
            model_name='appuser',
            index=models.Index(
                fields=['last_name', 'first_name'], name='idx_name_combo'),
        ),
        migrations.AddIndex(
            model_name='appuser',
            index=models.Index(
                fields=['customer_id', 'created'], name='idx_customer_created'),
        ),
        migrations.AddIndex(
            model_name='customerrelationship',
            index=models.Index(
                fields=['appuser', 'points'], name='idx_user_points'),
        ),
    ]
