# Generated by Django 5.0.6 on 2025-11-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='address',
            name='city_code',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='customer_id',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='gender',
            field=models.CharField(
                choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='phone_number',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='customerrelationship',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
